export {default as Home} from './Home'
export {default as Navbar} from './Navbar'
export {default as Footer} from './Footer'
export {default as SearchForm} from './SearchForm'
export {default as MainInfo} from './MainInfo'
export {default as JustList} from './JustList'
export {default as SubInfo} from './SubInfo'
export {default as SideBar} from './SideBar'